# \file
# \brief Constants for the ii rules. If architecture changes, only
#        this file needs be adapted
#
# \author    Paul Frederiks
# \author    Lazlo Westerhof
# \copyright Copyright (c) 2016-2018, Utrecht University. All rights reserved.
# \license   GPLv3, see LICENSE.

# \constant GENQMAXROWS Maximum number of rows returned by an iRODS GenQuery or msiGetMoreRows call
GENQMAXROWS = 256

#\brief the length of the search string should be below 1075, as this hits the MAX_SQL_SIZE limit in iRODS.
#       The search field is limited to 255 characters to be consistent with the metadata text field maxLength
#       255 * 4 = 1020 bytes when all characters are 4 byte utf-8 encoded, like in chinese.
#\constant IIMAXSEARCHSTRINGLENGTH
IIMAXSEARCHSTRINGLENGTH = 1020;

# \constant IIGROUPPREFIX
IIGROUPPREFIX = "research-"

# \constant IIVAULTPREFIX
IIVAULTPREFIX = "vault-"

# \constant IILICENSECOLLECTION
IILICENSECOLLECTION = UUSYSTEMCOLLECTION ++ "/licenses"

# \constant IITERMSCOLLECTION
IITERMSCOLLECTION = UUSYSTEMCOLLECTION ++ "/terms"

# \constant IISCHEMACOLLECTION
IISCHEMACOLLECTION = UUSYSTEMCOLLECTION ++ "/schemas"

# \constant IIDEFAULTSCHEMANAME
IIDEFAULTSCHEMANAME = "default"

# \constant IIMETADATAXMLNAME
IIMETADATAXMLNAME = "yoda-metadata.xml"

# \constant IIJSONNAME Name of the metadata JSON
IIJSONNAME = "metadata.json"

# \constant IIRESEARCHXSDNAME Name of the research XSD
IIRESEARCHXSDNAME = "research.xsd"

# \constant IIVAULTXSDNAME Name of the vault XSD
IIVAULTXSDNAME = "vault.xsd"

# \constant IIAVUXSLNAME Name of the AVU XSLT
IIAVUXSLNAME = "avu.xsl"

# \constant IIDATACITEXSLNAME Name of the datacite XSLT
IIDATACITEXSLNAME = "datacite.xsl"

# \constant IILANDINGPAGEXSLNAME Name of the landingpage XSLT
IILANDINGPAGEXSLNAME = "landingpage.xsl"

# \constant IIEMPTYLANDINGPAGEXSLNAME Name of the empty landingpage XSLT
IIEMPTYLANDINGPAGEXSLNAME = "emptylandingpage.xsl"

# \constant IIPUBLICATIONCOLLECTION
IIPUBLICATIONCOLLECTION = UUSYSTEMCOLLECTION ++ "/publication"

# \constant IILOCKATTRNAME
IILOCKATTRNAME = UUORGMETADATAPREFIX ++ "lock"

# \constant IISTATUSATTRNAME
IISTATUSATTRNAME = UUORGMETADATAPREFIX ++ "status"

# \constant IICOPYPARAMSNAME
IICOPYPARAMSNAME = UUORGMETADATAPREFIX ++ "copy_to_vault_params"

# \constant IIVAULTSTATUSATTRNAME
IIVAULTSTATUSATTRNAME = UUORGMETADATAPREFIX ++ "vault_status"

# \brief All research folder states.
FOLDER = "";
LOCKED = "LOCKED";
SUBMITTED = "SUBMITTED";
ACCEPTED = "ACCEPTED";
REJECTED = "REJECTED";
SECURED = "SECURED";

# \constant IIFOLDERTRANSITIONS
IIFOLDERTRANSITIONS = list((FOLDER, LOCKED),
			   (FOLDER, SUBMITTED),
			   (LOCKED, FOLDER),
			   (LOCKED, SUBMITTED),
			   (SUBMITTED, FOLDER),
			   (SUBMITTED, ACCEPTED),
			   (SUBMITTED, REJECTED),
			   (REJECTED, LOCKED),
			   (REJECTED, FOLDER),
			   (REJECTED, SUBMITTED),
			   (ACCEPTED, SECURED),
			   (SECURED, LOCKED),
			   (SECURED, FOLDER),
			   (SECURED, SUBMITTED))

# \brief All vault package states.
INCOMPLETE = "INCOMPLETE"
COMPLETE = "COMPLETE"
UNPUBLISHED = "UNPUBLISHED";
SUBMITTED_FOR_PUBLICATION = "SUBMITTED_FOR_PUBLICATION";
APPROVED_FOR_PUBLICATION = "APPROVED_FOR_PUBLICATION";
PUBLISHED = "PUBLISHED";
PENDING_DEPUBLICATION = "PENDING_DEPUBLICATION";
DEPUBLISHED = "DEPUBLISHED";
PENDING_REPUBLICATION = "PENDING_REPUBLICATION";

# \constant IIVAULTTRANSITIONS
IIVAULTTRANSITIONS = list((UNPUBLISHED, SUBMITTED_FOR_PUBLICATION),
			  (COMPLETE, SUBMITTED_FOR_PUBLICATION),
			  (SUBMITTED_FOR_PUBLICATION, APPROVED_FOR_PUBLICATION),
			  (SUBMITTED_FOR_PUBLICATION, UNPUBLISHED),
			  (APPROVED_FOR_PUBLICATION, PUBLISHED),
			  (PUBLISHED, PENDING_DEPUBLICATION),
			  (PENDING_DEPUBLICATION, DEPUBLISHED),
			  (DEPUBLISHED, PENDING_REPUBLICATION),
			  (PENDING_REPUBLICATION, PUBLISHED))

# \brief All cronjob states.
CRONJOB_PENDING = "CRONJOB_PENDING"
CRONJOB_PROCESSING = "CRONJOB_PROCESSING"
CRONJOB_RETRY = "CRONJOB_RETRY"
CRONJOB_UNRECOVERABLE = "CRONJOB_UNRECOVERABLE"
CRONJOB_OK = "CRONJOB_OK"
