"""Unit tests for the pathutil utils module"""

__copyright__ = 'Copyright (c) 2023-2024, Utrecht University'
__license__   = 'GPLv3, see LICENSE'

import sys
from unittest import TestCase

sys.path.append('../util')

from pathutil import basename, chop, chopext, dirname, info, is_archived_datapackage_path, relpath, Space


class UtilPathutilTest(TestCase):

    def test_chop(self):
        output = chop("")
        self.assertEqual(output, ('/', ''))
        output = chop("/")
        self.assertEqual(output, ('/', ''))
        output = chop("/tempZone")
        self.assertEqual(output, ('', 'tempZone'))
        output = chop("/tempZone/yoda")
        self.assertEqual(output, ('/tempZone', 'yoda'))
        output = chop("/tempZone/home")
        self.assertEqual(output, ('/tempZone', 'home'))
        output = chop("/tempZone/home/rods")
        self.assertEqual(output, ('/tempZone/home', 'rods'))
        output = chop("/tempZone/home/research-test")
        self.assertEqual(output, ('/tempZone/home', 'research-test'))
        output = chop("/tempZone/home/research-test/test")
        self.assertEqual(output, ('/tempZone/home/research-test', 'test'))
        output = chop("/tempZone/home/research-test/test/file.txt")
        self.assertEqual(output, ('/tempZone/home/research-test/test', 'file.txt'))

    def test_dirname(self):
        output = dirname("")
        self.assertEqual(output, '/')
        output = dirname("/")
        self.assertEqual(output, '/')
        output = dirname("/tempZone")
        self.assertEqual(output, '')
        output = dirname("/tempZone/yoda")
        self.assertEqual(output, '/tempZone')
        output = dirname("/tempZone/home")
        self.assertEqual(output, '/tempZone')
        output = dirname("/tempZone/home/rods")
        self.assertEqual(output, '/tempZone/home')
        output = dirname("/tempZone/home/research-test")
        self.assertEqual(output, '/tempZone/home')
        output = dirname("/tempZone/home/research-test/test")
        self.assertEqual(output, '/tempZone/home/research-test')
        output = dirname("/tempZone/home/research-test/test/file.txt")
        self.assertEqual(output, '/tempZone/home/research-test/test')

    def test_basename(self):
        output = basename("")
        self.assertEqual(output, '')
        output = basename("/")
        self.assertEqual(output, '')
        output = basename("/tempZone")
        self.assertEqual(output, 'tempZone')
        output = basename("/tempZone/yoda")
        self.assertEqual(output, 'yoda')
        output = basename("/tempZone/home")
        self.assertEqual(output, 'home')
        output = basename("/tempZone/home/rods")
        self.assertEqual(output, 'rods')
        output = basename("/tempZone/home/research-test")
        self.assertEqual(output, 'research-test')
        output = basename("/tempZone/home/research-test/test")
        self.assertEqual(output, 'test')
        output = basename("/tempZone/home/research-test/test/file.txt")
        self.assertEqual(output, 'file.txt')

    def test_chopext(self):
        output = chopext("")
        self.assertEqual(output, [''])
        output = chopext("/")
        self.assertEqual(output, ['/'])
        output = chopext("/tempZone")
        self.assertEqual(output, ['/tempZone'])
        output = chopext("/tempZone/yoda")
        self.assertEqual(output, ['/tempZone/yoda'])
        output = chopext("/tempZone/home")
        self.assertEqual(output, ['/tempZone/home'])
        output = chopext("/tempZone/home/rods")
        self.assertEqual(output, ['/tempZone/home/rods'])
        output = chopext("/tempZone/home/research-test")
        self.assertEqual(output, ['/tempZone/home/research-test'])
        output = chopext("/tempZone/home/research-test/test")
        self.assertEqual(output, ['/tempZone/home/research-test/test'])
        output = chopext("/tempZone/home/research-test/test/file.txt")
        self.assertEqual(output, ['/tempZone/home/research-test/test/file', 'txt'])

    def test_info(self):
        output = info("")
        self.assertEqual(output, (Space.OTHER, '', '', ''))
        output = info("/")
        self.assertEqual(output, (Space.OTHER, '', '', ''))
        output = info("/tempZone")
        self.assertEqual(output, (Space.OTHER, 'tempZone', '', ''))
        output = info("/tempZone/yoda")
        self.assertEqual(output, (Space.OTHER, 'tempZone', '', 'yoda'))
        output = info("/tempZone/home")
        self.assertEqual(output, (Space.OTHER, 'tempZone', '', 'home'))
        output = info("/tempZone/home/rods")
        self.assertEqual(output, (Space.OTHER, 'tempZone', 'rods', ''))
        output = info("/tempZone/home/research-test")
        self.assertEqual(output, (Space.RESEARCH, 'tempZone', 'research-test', ''))
        output = info("/tempZone/home/research-test/test")
        self.assertEqual(output, (Space.RESEARCH, 'tempZone', 'research-test', 'test'))
        output = info("/tempZone/home/research-test/test/file.txt")
        self.assertEqual(output, (Space.RESEARCH, 'tempZone', 'research-test', 'test/file.txt'))
        output = info("/tempZone/home/vault-test")
        self.assertEqual(output, (Space.VAULT, 'tempZone', 'vault-test', ''))
        output = info("/tempZone/home/datamanager-test")
        self.assertEqual(output, (Space.DATAMANAGER, 'tempZone', 'datamanager-test', ''))
        output = info("/tempZone/home/deposit-test")
        self.assertEqual(output, (Space.DEPOSIT, 'tempZone', 'deposit-test', ''))
        output = info("/tempZone/home/intake-test")
        self.assertEqual(output, (Space.INTAKE, 'tempZone', 'intake-test', ''))
        output = info("/tempZone/home/grp-intake-test")
        self.assertEqual(output, (Space.INTAKE, 'tempZone', 'grp-intake-test', ''))
        output = info("/tempZone/home/datarequests-test")
        self.assertEqual(output, (Space.DATAREQUEST, 'tempZone', 'datarequests-test', ''))

    def test_is_archived_datapackage_path(self):
        self.assertTrue(is_archived_datapackage_path("/tempZone/home/vault-foo/datapackage[123456]"))
        self.assertTrue(is_archived_datapackage_path("/tempZone/home/vault-foo/data-package[123456]"))
        self.assertTrue(is_archived_datapackage_path("/tempZone/home/vault-foo/data package[123456]"))
        self.assertFalse(is_archived_datapackage_path("/tempZone/home/vault-foo/collectionwithouttimestamp"))
        self.assertFalse(is_archived_datapackage_path("/tempZone/home/research-foo/tempZone/home/vault-foo/datapackage[123456]"))
        self.assertFalse(is_archived_datapackage_path("/tempZone/home/vault-foo/datapackage[123456]/original"))
        self.assertFalse(is_archived_datapackage_path("/tempZone/trash/home/vault-foo/datapackage[123456]"))
        self.assertFalse(is_archived_datapackage_path("/tempZone/yoda/schemas/default-0"))
        self.assertFalse(is_archived_datapackage_path("/tempZone/home/research-foo"))
        self.assertFalse(is_archived_datapackage_path("/tempZone/home/vault-foo"))
        self.assertFalse(is_archived_datapackage_path("/tempZone"))
        self.assertFalse(is_archived_datapackage_path(""))

    def test_relpath(self):
        self.assertEqual(relpath("/foo/bar", "/foo/bar"), ".")
        self.assertEqual(relpath("/foo/bar/bat", "/foo/bar"), "bat")
        self.assertEqual(relpath("/foo/bar/bat/ball", "/foo/bar"), "bat/ball")
