#!/bin/bash
PHYPATH=$1
HOST=$2
USER=$3
PRIVATEKEY=$4
DESTINATION=$5
echo "Calling:"
echo "scp -i $HOME/.ssh/$4 $PHYPATH $USER@$HOST:$DESTINATION"
scp -i $HOME/.ssh/$4 $PHYPATH $USER@$HOST:$DESTINATION
