name: Generate API documentation

on:
  push:
    branches:
    - development
    paths-ignore:
    - 'file_formats/**'
    - 'licenses/**'
    - 'schemas/**'
    - 'templates/**'
    - 'terms/**'
    - 'tests/**'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [2.7]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        # setup-python stopped supporting Python 2.7, use https://github.com/MatteoH2O1999/setup-python
        uses: MatteoH2O1999/setup-python@v3.2.1
        with:
          python-version: ${{ matrix.python-version }}
          allow-build: info
          cache-build: true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install openapi-spec-validator
          python -m pip install -r requirements.txt

      - name: Create directory for API documentation
        run: |
          mkdir build
          ln -s . rules_uu

      - name: Generate Yoda core API documentation
        run: |
          export PYTHONPATH="${PYTHONPATH}:."
          python tools/api/generate-openapi.py rules_uu --core > build/api_core.json

      - name: Validate Yoda core API documentation
        run: |
          openapi-spec-validator build/api_core.json

      - name: Generate Yoda module API documentation
        run: |
          export PYTHONPATH="${PYTHONPATH}:."
          python tools/api/generate-openapi.py rules_uu --module datarequest > build/api_datarequest.json
          python tools/api/generate-openapi.py rules_uu --module deposit > build/api_deposit.json
          python tools/api/generate-openapi.py rules_uu --module intake > build/api_intake.json

      - name: Validate Yoda module API documentation
        run: |
          openapi-spec-validator build/api_datarequest.json
          openapi-spec-validator build/api_deposit.json
          openapi-spec-validator build/api_intake.json

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build/
