name: "Validate schemas"

on:
  push:
    paths:
    - 'schemas/**'
    - 'datarequest/schemas/**'
  pull_request:
    paths:
    - 'schemas/**'
    - 'datarequest/schemas/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install ajv-cli
        run: |
          npm install -g ajv-cli

      - name: Validate JSON schemas
        run: |
          ajv compile -s "schemas/{core-0,core-1,dag-0,default-0,default-1,default-2,epos-msl-0,hptlab-0,hptlab-1,teclab-0,teclab-1,vocabulary-0,vollmer-0}/metadata.json" --spec=draft7 --strict=false --validate-formats=false
          ajv compile -s "schemas/{core-0,core-1,dag-0,default-0,default-1,default-2,epos-msl-0,hptlab-0,hptlab-1,teclab-0,teclab-1,vocabulary-0,vollmer-0}/uischema.json" --spec=draft7 --strict=false --validate-formats=false

          ajv compile -s "schemas/{core-2,default-3}/metadata.json" --spec=draft2019 --strict=false --validate-formats=false
          ajv compile -s "schemas/{core-2,default-3}/uischema.json" --spec=draft2019 --strict=false --validate-formats=false

          ajv compile -s "datarequest/schemas/*/*/*.json"  --spec=draft7 --strict=false --validate-formats=false
