name: "Run unit tests"

on:
  push:
    paths-ignore:
    - 'tests/**'
  pull_request:
    paths-ignore:
    - 'tests/**'

jobs:
  unit-tests:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        python_version: [ '3.9', '3.12' ]

    steps:
      - uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run unit tests
        run: |
          cd unit-tests
          export PYTHONPATH=$(cd ../util ; pwd):$PYTHONPATH
          coverage run --source=..,../util --omit=test_*.py,unit_tests.py -m unittest unit_tests

      - name: Report code coverage
        run: |
          cd unit-tests
          coverage report
