name: "Run unit tests"

on:
  push:
    paths-ignore:
    - 'tests/**'
  pull_request:
    paths-ignore:
    - 'tests/**'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        # setup-python stopped supporting Python 2.7, use https://github.com/MatteoH2O1999/setup-python
        uses: MatteoH2O1999/setup-python@v4.0.1
        with:
          python-version: ${{ matrix.python-version }}
          allow-build: info
          cache-build: true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install coveragepy==1.6.0

      - name: Run unit tests
        run: |
          cd unit-tests
          coverage run --omit=test_*.py,unit_tests.py --source=$(cd .. ; pwd),$(cd ../util ; pwd) -m unittest unit_tests

      - name: Report code coverage
        run: |
          cd unit-tests
          coverage report
