name: "Run unit tests"

on:
  push:
    paths-ignore:
    - 'tests/**'
  pull_request:
    paths-ignore:
    - 'tests/**'

jobs:
  flake8:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        # setup-python stopped supporting Python 2.7, use https://github.com/MatteoH2O1999/setup-python
        uses: MatteoH2O1999/setup-python@v1.4.1
        with:
          python-version: ${{ matrix.python-version }}
          allow-build: info
          cache-build: true

      - name: Run unit tests
        run: |
          cd unit-tests
          python2 -m unittest unit_tests
